import { readFileSync, writeFileSync } from 'node:fs';
const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const source = ['preamble.js', 'carousel.js', 'editor.js'].map(name => readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8')).join('\n');
writeFileSync(new URL('../rss-labswill-ha.js', import.meta.url), `// RSS LabsWill HA v${version} — generated by npm run build\n${source}`);
